name: Docker Autobuild
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"

jobs:
  docker:
    name: Docker Autobuild
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - channel: stable
            tag: 1.20.9
            latest: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log in to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Lowercase repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
      - name: Set image tags
        id: tags
        run: |
          TAGS="ghcr.io/${{ env.REPO }}:${{matrix.version.channel}}-${{ matrix.version.tag }}"
          if [[ "${{ matrix.version.channel }}" == "stable" ]]; then
            TAGS+=",ghcr.io/${{ env.REPO }}:${{ matrix.version.tag }}"
          fi
          if [[ "${{ matrix.version.latest }}" == "true" ]]; then
            TAGS+=",ghcr.io/${{ env.REPO }}:latest"
          fi
          echo "TAGS=$TAGS" >> $GITHUB_OUTPUT
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          no-cache: true
          build-args: |-
            CHANNEL=${{ matrix.version.channel }}
            VERSION=${{ matrix.version.tag }}
          tags: ${{ steps.tags.outputs.TAGS }}
